jobs:
- job: macOS

  pool:
    vmImage: 'macOS-latest'

  strategy:
    maxParallel: 3
    matrix:
      Python35:
        python.version: '3.5'

      Python36:
        python.version: '3.6'

      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Setting Python version'

  - script: brew cask install gfortran
    displayName: 'Installing Fortran'

  - template: build_and_deploy.yml
